image:
  file: .gitpod.Dockerfile
ports:
- port: 8888
  onOpen: ignore
tasks:
- init: cp -r $GITPOD_REPO_ROOT/.jupyter ~
- command: jupyter notebook --no-browser
  name: Jupyter Notebook Server
  openIn: main
  openMode: split-right
