image:
  file: .gitpod.Dockerfile
ports:
- port: 8888
  onOpen: open-browser
tasks:
- init: cp -r $GITPOD_REPO_ROOT./jupyter ~
- command: jupyter notebook
  name: Jupyter Notebook Server
  # Should capture the opener url and maybe open
